[project]
name = "livekit-openai-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nick Cao", email = "ncao@redhat.com" }
]
requires-python = ">=3.14"
dependencies = [
    "livekit-agents[openai]>=1.8.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
livekit-openai-test = "livekit_openai_test:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
